# Week 1 - Monthly Dataset Aggregation

Given monthly MLS files, concatenate all files from January 2024 onwards into combined dataset

In [ ]:
import pandas as pd
from pathlib import Path
from matplotlib import pyplot as plt
import seaborn as sns

In [ ]:
# set path to data folder
data_dir = Path("../data/raw_csv")

First, I'll sort the listing csv's by concatenation then filtering based on "Residential" Property Type. Then, I'll do the same thing with the sold csv's and then concatenate the filtered dataframes.

In [ ]:
# grab all the "listing" csv files in the data folder
listing_files = sorted(data_dir.glob("CRMLSListing*.csv")) # avoid hard coding the file names
print(len(listing_files), "CRMLS Listing files found:")
listing_files

28 CRMLS Listing files found:

[PosixPath('../data/raw_csv/CRMLSListing202401.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202402.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202403.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202404.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202405.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202406.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202407.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202408.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202409.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202410.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202411.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202412.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202501.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202502.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202503.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202504.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202505.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202506.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202507.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202508.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202509.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202510.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202511.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202512.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202601.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202602.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202603.csv'),
 PosixPath('../data/raw_csv/CRMLSListing202604.csv')]

In [3]:
# now grab all the "sold" csv files in the data folder
sold_files = sorted(data_dir.glob("CRMLSSold*.csv"))
print(len(sold_files), "CRMLS Sold files found:")
sold_files

28 CRMLS Sold files found:

[PosixPath('../data/raw_csv/CRMLSSold202401_filled.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202402.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202403_filled.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202404_filled.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202405_filled.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202406_filled.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202407_filled.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202408.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202409.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202410.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202411.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202412.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202501_filled.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202502.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202503.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202504.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202505.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202506.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202507.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202508.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202509.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202510.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202511.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202512.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202601.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202602.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202603.csv'),
 PosixPath('../data/raw_csv/CRMLSSold202604.csv')]

### Listing DF
Now we need to read in each file in so we can create a list of the "listing" data to prepare for concatenation.
Additionally, we must confirm that the row counts from before and after concatenation are the same.

In [4]:
# empty list to hold the dataframes for each listing file
listing_df = []

# read in each listing file, then append it to listing_df
for file in listing_files:
    df = pd.read_csv(file, low_memory=False)
    listing_df.append(df)

    # print out name of file and # of rows and cols after each file is read in
    print(file.name, "->", len(df), "ROWS and", len(df.columns), "COLS")

CRMLSListing202401.csv -> 12895 ROWS and 84 COLS
CRMLSListing202402.csv -> 27447 ROWS and 84 COLS
CRMLSListing202403.csv -> 8030 ROWS and 84 COLS
CRMLSListing202404.csv -> 36503 ROWS and 84 COLS
CRMLSListing202405.csv -> 38796 ROWS and 82 COLS
CRMLSListing202406.csv -> 35893 ROWS and 82 COLS
CRMLSListing202407.csv -> 36340 ROWS and 82 COLS
CRMLSListing202408.csv -> 35305 ROWS and 82 COLS
CRMLSListing202409.csv -> 34625 ROWS and 82 COLS
CRMLSListing202410.csv -> 34730 ROWS and 82 COLS
CRMLSListing202411.csv -> 25128 ROWS and 82 COLS
CRMLSListing202412.csv -> 19417 ROWS and 82 COLS
CRMLSListing202501.csv -> 37469 ROWS and 82 COLS
CRMLSListing202502.csv -> 33983 ROWS and 82 COLS
CRMLSListing202503.csv -> 38492 ROWS and 82 COLS
CRMLSListing202504.csv -> 40187 ROWS and 82 COLS
CRMLSListing202505.csv -> 40271 ROWS and 82 COLS
CRMLSListing202506.csv -> 26399 ROWS and 82 COLS
CRMLSListing202507.csv -> 27345 ROWS and 82 COLS
CRMLSListing202508.csv -> 25210 ROWS and 82 COLS
CRMLSListing202509.csv -> 26923 ROWS and 82 COLS
CRMLSListing202510.csv -> 27586 ROWS and 82 COLS
CRMLSListing202511.csv -> 20677 ROWS and 82 COLS
CRMLSListing202512.csv -> 18773 ROWS and 82 COLS
CRMLSListing202601.csv -> 2606 ROWS and 82 COLS
CRMLSListing202602.csv -> 32884 ROWS and 82 COLS
CRMLSListing202603.csv -> 39153 ROWS and 82 COLS
CRMLSListing202604.csv -> 39020 ROWS and 82 COLS

In [5]:
# get the total number of rows in all the listing files
listings_rows_before = sum(len(df) for df in listing_df)
print(listings_rows_before)

822087

In [6]:
# concatenate all the listing dataframes into one dataframe
listings = pd.concat(listing_df, ignore_index=True)
listings

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
0,90000.0,1075010398,miriamlara03@gmail.com,NaN,NaN,Miriam,Lara,34.097939,-117.909653,1045 N Azusa 61,...,NaN,NaN,2.0,Covina Valley Unified,91722,NaN,0.0,NaN,NaN,1045 N Azusa 61
1,1500000.0,1074974457,janelle@judsonre.com,NaN,NaN,Janelle,Judson,33.121241,-117.081614,NaN,...,NaN,NaN,NaN,NaN,92025,NaN,0.0,NaN,NaN,NaN
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,NaN,2105.0,177861.0,NaN,2220 Avenue Of The Stars 2704
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,NaN,254.0,5300.0,NaN,16 Palisades
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822082,1375000.0,1151355330,ammarkosgroup@gmail.com,NaN,NaN,Athir,Markos,32.811131,-116.946359,1161 N Anza Street,...,NaN,NaN,NaN,NaN,92021,NaN,0.0,222156.0,NaN,1161 N Anza Street
822083,985000.0,1149517845,aisaethan@icloud.com,NaN,NaN,Aisa,Tu,33.645255,-117.358172,33115 Evergreen Sreet,...,2.0,NaN,3.0,Lake Elsinore Unified,92530,NaN,0.0,14810.0,NaN,33115 Evergreen Sreet
822084,450000.0,1147219386,nathaly@shoppingsdhouses.com,NaN,NaN,Nathaly,Vera,32.746368,-116.984283,9860 Dale Avenue D2,...,NaN,NaN,0.0,Other,91977,NaN,510.0,91040.4,NaN,9860 Dale Avenue D2
822085,249000.0,1145273331,BillSoCalCoast@gmail.com,NaN,NaN,Bill,Church,33.229747,-117.127269,Little Canyon Lane,...,NaN,NaN,NaN,NaN,92026,NaN,210.0,37897.0,NaN,Little Canyon Lane
822086,1056400.0,1144232364,brokerosborne@gmail.com,2026-02-05,965200.0,John,Osborne,33.637915,-114.575821,9165 Intake Boulevard,...,NaN,NaN,NaN,NaN,92225,SimpliHOM,NaN,3445160.0,NaN,9165 Intake Boulevard

In [ ]:
print("# Listing Rows Before Concat:", listings_rows_before)
print("# Listing Rows After Concat:", len(listings))

# Listing Rows Before Concat: 822087
# Listing Rows After Concat: 822087

In [16]:
listings["PropertyType"].value_counts()

PropertyType
Residential            522931
ResidentialLease       170798
Land                    53337
ResidentialIncome       30535
ManufacturedInPark      23431
CommercialSale          11095
CommercialLease          7343
BusinessOpportunity      2615
Resid                       1
Name: count, dtype: int64

In [24]:
# now filter based on the PropertyType == "Residential"
listings_before_filter = len(listings)

listings_residential = listings[listings["PropertyType"] == "Residential"].copy()

print("# Listing Rows Before 'Residential' Filter: ", listings_before_filter)
print("# Listing Rows After 'Residential' Filter:", len(listings_residential))

listings_residential

# Listing Rows Before 'Residential' Filter:  822087
# Listing Rows After 'Residential' Filter: 522931

,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,ListAgentFirstName,ListAgentLastName,Latitude,Longitude,UnparsedAddress,...,MainLevelBedrooms,NewConstructionYN,GarageSpaces,HighSchoolDistrict,PostalCode,BuyerOfficeName.1,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,UnparsedAddress.1
2,1340000.0,1074973329,haleh360@Gmail.com,NaN,NaN,Haleh,Dowlatshahi,34.052207,-118.408445,2220 Avenue Of The Stars 2704,...,NaN,False,NaN,NaN,90067,NaN,2105.00,177861.0,NaN,2220 Avenue Of The Stars 2704
3,2500000.0,1074954552,Reneechen@yourhomesoldguaranteed.com,NaN,NaN,Renee,Chen,33.496363,-117.691677,16 Palisades,...,0.0,False,3.0,Capistrano Unified,92677,NaN,254.00,5300.0,NaN,16 Palisades
4,3150000.0,1074936537,anader@dppre.com,NaN,NaN,Margaret,Nader,34.119345,-118.111254,1615 Waverly Road,...,NaN,NaN,2.0,NaN,91108,NaN,NaN,9404.0,NaN,1615 Waverly Road
5,3090000.0,1074917818,QIANYU0607@GMAIL.COM,NaN,NaN,QIANYU,GUAN,33.984057,-117.802819,2250 Indian Creek Road,...,1.0,False,4.0,Walnut Valley Unified,91765,NaN,295.95,58232.0,NaN,2250 Indian Creek Road
6,12725000.0,1074143166,jeff.williams@pacificsir.com,NaN,NaN,Jeff,Williams,33.607583,-117.887743,317 E. Bayfront,...,3.0,False,2.0,Newport Mesa Unified,92662,NaN,0.00,2250.0,NaN,317 E. Bayfront
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
822075,2595000.0,1153444674,denny@dennykagasoff.com,NaN,NaN,Denny,Kagasoff,34.129724,-118.394741,12004 Briarvale Lane,...,NaN,False,NaN,NaN,91604,NaN,NaN,24226.0,NaN,12004 Briarvale Lane
822077,7285000.0,1152609167,ann@brizolisjanzen.com,NaN,NaN,K. Ann,Brizolis,32.980315,-117.198367,14480 Bellvista Dr,...,NaN,False,3.0,NaN,92067,NaN,735.00,NaN,NaN,14480 Bellvista Dr
822081,396000.0,1151471220,jason@venture-pacific.net,NaN,NaN,Jason,Lipovsky,33.002752,-116.782659,15755 Davis Cup Lane,...,1.0,NaN,0.0,Ramona Unified,92065,NaN,596.00,831560.4,NaN,15755 Davis Cup Lane
822083,985000.0,1149517845,aisaethan@icloud.com,NaN,NaN,Aisa,Tu,33.645255,-117.358172,33115 Evergreen Sreet,...,2.0,NaN,3.0,Lake Elsinore Unified,92530,NaN,0.00,14810.0,NaN,33115 Evergreen Sreet
822084,450000.0,1147219386,nathaly@shoppingsdhouses.com,NaN,NaN,Nathaly,Vera,32.746368,-116.984283,9860 Dale Avenue D2,...,NaN,NaN,0.0,Other,91977,NaN,510.00,91040.4,NaN,9860 Dale Avenue D2

### Sold DF
Now just do the same thing but with the Sold CSV files. Just follow the same steps.

In [9]:
sold_dfs = []

for file in sold_files:
    df = pd.read_csv(file, low_memory=False)
    sold_dfs.append(df)

    print(file.name, "->", len(df), "ROWS and", len(df.columns), "COLS")

CRMLSSold202401_filled.csv -> 17958 ROWS and 80 COLS
CRMLSSold202402.csv -> 19925 ROWS and 78 COLS
CRMLSSold202403_filled.csv -> 23276 ROWS and 80 COLS
CRMLSSold202404_filled.csv -> 24640 ROWS and 80 COLS
CRMLSSold202405_filled.csv -> 26487 ROWS and 80 COLS
CRMLSSold202406_filled.csv -> 24328 ROWS and 80 COLS
CRMLSSold202407_filled.csv -> 26240 ROWS and 80 COLS
CRMLSSold202408.csv -> 24558 ROWS and 78 COLS
CRMLSSold202409.csv -> 21267 ROWS and 78 COLS
CRMLSSold202410.csv -> 23274 ROWS and 78 COLS
CRMLSSold202411.csv -> 20279 ROWS and 78 COLS
CRMLSSold202412.csv -> 20241 ROWS and 78 COLS
CRMLSSold202501_filled.csv -> 18738 ROWS and 80 COLS
CRMLSSold202502.csv -> 18702 ROWS and 78 COLS
CRMLSSold202503.csv -> 21445 ROWS and 78 COLS
CRMLSSold202504.csv -> 23262 ROWS and 78 COLS
CRMLSSold202505.csv -> 23154 ROWS and 78 COLS
CRMLSSold202506.csv -> 22883 ROWS and 78 COLS
CRMLSSold202507.csv -> 23646 ROWS and 78 COLS
CRMLSSold202508.csv -> 22972 ROWS and 78 COLS
CRMLSSold202509.csv -> 22443 ROWS and 78 COLS
CRMLSSold202510.csv -> 23233 ROWS and 78 COLS
CRMLSSold202511.csv -> 19088 ROWS and 78 COLS
CRMLSSold202512.csv -> 20538 ROWS and 78 COLS
CRMLSSold202601.csv -> 16487 ROWS and 78 COLS
CRMLSSold202602.csv -> 19010 ROWS and 80 COLS
CRMLSSold202603.csv -> 23372 ROWS and 80 COLS
CRMLSSold202604.csv -> 24261 ROWS and 80 COLS

In [11]:
# get the total # of rows in all the sold files before concatenation
sold_rows_before = sum(len(df) for df in sold_dfs)
print(sold_rows_before)

615707

In [13]:
# concatenate all the sold dataframes into one DF
sold = pd.concat(sold_dfs, ignore_index=True)
sold

,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,latfilled,lonfilled,BuyerAgentAOR,ListAgentAOR,OriginatingSystemName,OriginatingSystemSubName
0,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,94401,6472.0,NaN,NaN,True,True,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,0.0,535486633,eabrown@lee-associates.com,2024-01-24,950.0,...,92394,NaN,52320.0,NaN,False,False,NaN,NaN,NaN,NaN
2,NaN,True,NaN,NaN,NaN,75000.0,529986282,Joe@9WINWIN.com,2024-01-16,45000.0,...,93240,NaN,217364.0,NaN,False,False,NaN,NaN,NaN,NaN
3,NaN,True,NaN,NaN,NaN,199000.0,529618166,carolthefinder@yahoo.com,2024-01-08,141500.0,...,92308,NaN,217800.0,NaN,False,False,NaN,NaN,NaN,NaN
4,NaN,True,NaN,NaN,NaN,19500.0,522614340,jtavisola@tavisola.com,2024-01-17,15000.0,...,93544,0.0,108883.0,NaN,False,False,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615702,NaN,True,NaN,NaN,NaN,200000.0,1014741959,dtownsendrealestate@gmail.com,2026-04-20,85000.0,...,95916,0.0,910839.6,NaN,NaN,NaN,SierraNorthValley,SierraNorthValley,CRMLS,CRMLS_CRM
615703,NaN,True,NaN,NaN,NaN,97500.0,1002540286,scott@westcoe.com,2026-04-03,85000.0,...,92539,0.0,522720.0,NaN,NaN,NaN,SouthwestRiversideCounty,InlandValleys,CRMLS,CRMLS_CRM
615704,NaN,True,NaN,NaN,NaN,15999.0,482785043,mr.khatibi@yahoo.com,2026-04-28,19000.0,...,93551,0.0,20009.0,NaN,NaN,NaN,Mrmls,Southland,CRMLS,CRMLS_CRM
615705,NaN,True,NaN,NaN,NaN,6000000.0,446619807,jeffnyal@gmail.com,2026-04-15,4500000.0,...,92882,NaN,122839.0,NaN,NaN,NaN,OrangeCounty,HighDesert,CRMLS,CRMLS_CRM
615706,NaN,False,NaN,NaN,False,NaN,431883449,PABLOANS@AOL.COM,2026-04-01,2100.0,...,91709,NaN,21780.0,NaN,NaN,NaN,CitrusValley,CitrusValley,CRMLS,CRMLS_CRM

In [14]:
print("# Sold Rows before Concat:", sold_rows_before)
print("# Sold Rows after Concat:", len(sold))

# Sold Rows before Concat: 615707
# Sold Rows after Concat: 615707

In [17]:
sold["PropertyType"].value_counts()

PropertyType
Residential            414054
ResidentialLease       140960
Land                    20038
ManufacturedInPark      16706
ResidentialIncome       16476
CommercialSale           3843
CommercialLease          3216
BusinessOpportunity       414
Name: count, dtype: int64

In [25]:
# now filter Sold csv based on the PropertyType == "Residential"
sold_before_filter = len(sold)
sold_residential = sold[sold["PropertyType"] == "Residential"].copy()

print("# Sold Rows Before 'Residential' Filter: ", sold_before_filter)
print("# Sold Rows After 'Residential' Filter:", len(sold_residential))

sold_residential

# Sold Rows Before 'Residential' Filter:  615707
# Sold Rows After 'Residential' Filter: 414054

,Flooring,ViewYN,WaterfrontYN,BasementYN,PoolPrivateYN,OriginalListPrice,ListingKey,ListAgentEmail,CloseDate,ClosePrice,...,PostalCode,AssociationFee,LotSizeSquareFeet,MiddleOrJuniorSchoolDistrict,latfilled,lonfilled,BuyerAgentAOR,ListAgentAOR,OriginatingSystemName,OriginatingSystemSubName
0,"Carpet,Tile,Wood",True,NaN,NaN,False,499000.0,551985747,jwachter@cbnorcal.com,2024-01-26,240000.0,...,94401,6472.0,NaN,NaN,True,True,NaN,NaN,NaN,NaN
5,NaN,False,NaN,NaN,False,759900.0,522107581,mdarwich12@gmail.com,2024-01-05,815000.0,...,91950,NaN,NaN,NaN,True,True,NaN,NaN,NaN,NaN
9,NaN,False,NaN,NaN,False,739900.0,510919001,mdarwich12@gmail.com,2024-01-05,810000.0,...,91950,NaN,NaN,NaN,True,True,NaN,NaN,NaN,NaN
28,NaN,True,NaN,NaN,False,2100000.0,1067652762,jenniferarielkennedy@gmail.com,2024-01-02,2100000.0,...,93401,0.0,11219.0,NaN,False,False,NaN,NaN,NaN,NaN
29,Tile,True,NaN,NaN,False,1950000.0,1063453216,kira@mendosir.com,2024-01-22,1950000.0,...,95437,NaN,74487.6,NaN,False,False,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615675,NaN,True,NaN,True,False,279000.0,1069708148,jessica.homesells@gmail.com,2026-04-01,215000.0,...,95424,0.0,10019.0,NaN,NaN,NaN,LakeCounty,LakeCounty,CRMLS,CRMLS_CRM
615677,"Carpet,Tile,Wood",False,NaN,True,False,449000.0,1067010583,brian@cohen-realty.com,2026-04-13,415000.0,...,92322,0.0,12096.0,NaN,NaN,NaN,TheInlandGateway,TheInlandGateway,CRMLS,CRMLS_CRM
615680,Vinyl,True,NaN,NaN,False,1579000.0,1063196193,info@homecoin.com,2026-04-16,1355000.0,...,93619,0.0,859874.4,NaN,NaN,NaN,SanDiego,TriCounties,CRMLS,CRMLS_CRM
615681,NaN,True,NaN,NaN,False,855000.0,1062106215,jefflachef@gmail.com,2026-04-16,820000.0,...,92629,0.0,2733.0,NaN,NaN,NaN,Mrmls,OrangeCounty,CRMLS,CRMLS_CRM
615688,"Carpet,Vinyl",False,NaN,NaN,False,375000.0,1052387780,elizabethoryan04@gmail.com,2026-04-24,380000.0,...,90302,345.0,23878.0,NaN,NaN,NaN,Southland,PacificWest,CRMLS,CRMLS_CRM

Now that both listings and sold are sorted and concatenated, save both of them as CSVs.

In [ ]:
output_dir = Path("../data/processed_csv")
output_dir.mkdir(exist_ok=True)

listings_residential.to_csv(output_dir / "listings_residential.csv", index=False)

sold_residential.to_csv(output_dir / "sold_residential.csv",index=False)